export { default as CadetMainView } from "./CadetMainView.vue"
export { default as CadetListView } from "./CadetList.vue"
export { default as CadetItemView } from "./CadetItemView.vue"
export { default as CadetUpdateView } from "./CadetUpdateView.vue"
export { default as CadetListOkView } from "./CadetListOkView.vue"
