export { default as StudentMainView } from "./StudentMainView.vue"
export { default as StudentList } from "./StudentList.vue"
export { default as StudentItemView } from "./StudentItemView.vue"
export { default as StudentUpdateView } from "./StudentUpdateView.vue"
export { default as StudentDocsMakeView } from "./StudentDocsMakeView.vue"
