export { default as PassOfficeView } from "./PassOfficeView.vue"
export { default as PassOfficeCadetListView } from "./cadet/PassOfficeCadetListView.vue"
export { default as PassOfficeCadetItemView } from "./cadet/PassOfficeCadetItemView.vue"
export { default as PassOfficeStudentListView } from "./student/PassOfficeStudentListView.vue"
export { default as PassOfficeEmployeeListView } from "./employee/PassOfficeEmployeeListView.vue"
export { default as PassOfficeFPKPRKListView } from "./fpkprk/PassOfficeFPKPRKListView.vue"
